<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIPR68RA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIPR68RA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIPR68RA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIPR68RA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIPR68RA\App_KernelDevDebugContainer([
    'container.build_hash' => 'IPR68RA',
    'container.build_id' => '5e82da51',
    'container.build_time' => 1694605166,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIPR68RA');
