<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNDKqzCp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNDKqzCp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNDKqzCp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNDKqzCp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNDKqzCp\App_KernelDevDebugContainer([
    'container.build_hash' => 'NDKqzCp',
    'container.build_id' => '04284608',
    'container.build_time' => 1697030058,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNDKqzCp');
