<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Chambre extends \App\Entity\Chambre implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Chaine_a_laCarte' => [parent::class, 'Chaine_a_laCarte', null],
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null],
        "\0".parent::class."\0".'chainesDuCable' => [parent::class, 'chainesDuCable', null],
        "\0".parent::class."\0".'chainesSatellite' => [parent::class, 'chainesSatellite', null],
        "\0".parent::class."\0".'chambre' => [parent::class, 'chambre', null],
        "\0".parent::class."\0".'climatisation' => [parent::class, 'climatisation', null],
        "\0".parent::class."\0".'coffreFort' => [parent::class, 'coffreFort', null],
        "\0".parent::class."\0".'etat' => [parent::class, 'etat', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'libelle' => [parent::class, 'libelle', null],
        "\0".parent::class."\0".'materielDeRepassage' => [parent::class, 'materielDeRepassage', null],
        "\0".parent::class."\0".'superficie' => [parent::class, 'superficie', null],
        "\0".parent::class."\0".'tarif' => [parent::class, 'tarif', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        "\0".parent::class."\0".'television_a_ecranPlat' => [parent::class, 'television_a_ecranPlat', null],
        "\0".parent::class."\0".'vueSurMer' => [parent::class, 'vueSurMer', null],
        "\0".parent::class."\0".'wifiGratuit' => [parent::class, 'wifiGratuit', null],
        'Chaine_a_laCarte' => [parent::class, 'Chaine_a_laCarte', null],
        'categorie' => [parent::class, 'categorie', null],
        'chainesDuCable' => [parent::class, 'chainesDuCable', null],
        'chainesSatellite' => [parent::class, 'chainesSatellite', null],
        'chambre' => [parent::class, 'chambre', null],
        'climatisation' => [parent::class, 'climatisation', null],
        'coffreFort' => [parent::class, 'coffreFort', null],
        'etat' => [parent::class, 'etat', null],
        'id' => [parent::class, 'id', null],
        'libelle' => [parent::class, 'libelle', null],
        'materielDeRepassage' => [parent::class, 'materielDeRepassage', null],
        'superficie' => [parent::class, 'superficie', null],
        'tarif' => [parent::class, 'tarif', null],
        'telephone' => [parent::class, 'telephone', null],
        'television_a_ecranPlat' => [parent::class, 'television_a_ecranPlat', null],
        'vueSurMer' => [parent::class, 'vueSurMer', null],
        'wifiGratuit' => [parent::class, 'wifiGratuit', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
