<?php

namespace ContainerNDKqzCp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChambreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Chambre' shared autowired service.
     *
     * @return \App\Entity\Chambre
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'Chambre.php';

        return $container->privates['App\\Entity\\Chambre'] = new \App\Entity\Chambre();
    }
}
